version: '2'

services:
  benchmark-cli:
    image: php:8.0-cli-alpine3.12
    container_name: benchmark-cli
    networks:
      - benchmark
    volumes:
      - .:/code:cached
    env_file:
      - .env
    command: /code/build/container/cli/run.sh
    depends_on:
      - benchmark-nginx

  benchmark-nginx:
    image: nginx:1.21-alpine
    container_name: benchmark-nginx
    networks:
      - benchmark
    volumes:
      - .:/code:cached
    ports:
      - "8090:80"
    env_file:
      - .env
    command: /code/build/container/nginx/run.sh
    depends_on:
      - benchmark-fpm
    logging:
      driver: none

  benchmark-fpm:
    build: ./
    container_name: benchmark-fpm
    networks:
      - benchmark
    env_file:
      - .env
    command: /code/build/container/fpm/run.sh
    logging:
      driver: none

networks:
  benchmark:
